steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/api:latest'
      - '-t'
      - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/api:${_TAG}'
      - '--build-arg'
      - 'GIT_COMMIT=${_TAG}'
      - '--build-arg'
      - 'BUILD_SHA=${_TAG}'
      - '-f'
      - 'apps/api/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/web:latest'
      - '-t'
      - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/web:${_TAG}'
      - '--build-arg'
      - 'GIT_COMMIT=${_TAG}'
      - '--build-arg'
      - 'BUILD_SHA=${_TAG}'
      - '-f'
      - 'apps/web/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/worker:latest'
      - '-t'
      - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/worker:${_TAG}'
      - '--build-arg'
      - 'GIT_COMMIT=${_TAG}'
      - '--build-arg'
      - 'BUILD_SHA=${_TAG}'
      - '-f'
      - 'apps/worker/Dockerfile'
      - '.'

images:
  - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/api:latest'
  - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/api:${_TAG}'
  - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/web:latest'
  - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/web:${_TAG}'
  - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/worker:latest'
  - 'me-central1-docker.pkg.dev/e3-eos-staging/e3-eos/worker:${_TAG}'

substitutions:
  _TAG: '3ded6ef'

options:
  machineType: 'E2_HIGHCPU_8'
