services:
  - type: web
    name: e3-eos-api
    runtime: docker
    dockerfilePath: apps/api/Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"
