import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
const yaml=readFileSync(new URL('../contracts/CORE_COMMANDS.openapi.yaml',import.meta.url),'utf8');
function block(kind:string,indent:number){const start=yaml.indexOf('# BEGIN P01 SCHEDULE '+kind),end=yaml.indexOf('# END P01 SCHEDULE '+kind),text=yaml.slice(start,end),headers=[...text.matchAll(new RegExp(`^ {${indent}}([^\\n]+):\\n`,'gm'))];return Object.fromEntries(headers.map((h,i)=>[h[1],JSON.parse(text.slice(h.index!+h[0].length,headers[i+1]?.index??text.length).trim())]));}
const paths=block('CONTRACTS',2),schemas=block('SCHEMAS',4);
describe('Schedule API contract',()=>{
  it('keeps mirrors and route identities consistent',()=>{expect(yaml).toBe(readFileSync(new URL('../packages/contracts/CORE_COMMANDS.openapi.yaml',import.meta.url),'utf8'));expect(yaml).toContain('version: 1.8.0');const paths=[...yaml.matchAll(/^  (\/[^\n]+):$/gm)].map(m=>m[1]);expect(new Set(paths).size).toBe(paths.length);});
  it('binds forecast changes to both versions without baseline or actual fields',()=>{expect(schemas.ForecastChange.required).toEqual(expect.arrayContaining(['expectedTaskVersion','expectedForecastVersion','startAt','finishAt','timezone','reason']));expect(schemas.ForecastChange.additionalProperties).toBe(false);expect(schemas.ForecastChange.properties.startAt.anyOf).toContainEqual({type:'null'});for(const field of ['baselineStart','completedAt','isApproved'])expect(schemas.ForecastChange.properties).not.toHaveProperty(field);});
  it('documents durable authority and cycle rejection for dependencies',()=>{const op=paths['/projects/{projectId}/dependencies'].post;expect(op.responses).toHaveProperty('201');expect(op.responses).toHaveProperty('409');expect(op.description).toContain('cycles');expect(op.description).toContain('rechecked before receipt replay');expect(op.parameters.find((p:any)=>p.name==='Idempotency-Key')).toMatchObject({required:true});expect(schemas.ScheduleDependencyCreate.properties.dependencyType.enum).toEqual(['FS','SS','FF']);});
  it('discloses query boundaries, limits and archived history',()=>{const op=paths['/schedule/calendar'].get;expect(op.parameters.filter((p:any)=>p.in==='query').map((p:any)=>p.name)).toEqual(['from','until']);expect(op.description).toContain('366 days');expect(schemas.ForecastCalendarResult.properties.data.maxItems).toBe(1000);expect(schemas.ProjectTimelineResult.properties.data.properties.archivedDependencies.maxItems).toBe(200);expect(paths['/projects/{projectId}/dependencies/{id}/history'].get.description).toContain('after archiving');});
});
