/**
 * E3-EOS Canonical Stage Activity Library (312 Normative Activities)
 * Conforming to Master Developer Handover and stages/01 through 13.
 * Total: 13 stages x 24 activities = 312 unique activities.
 */

export type ActivityStatus = 'not_started' | 'in_progress' | 'completed' | 'blocked' | 'waived_by_exception';

export interface StageActivityDefinition {
  id: string; // e.g. "S01-01"
  stageNumber: number; // 1 to 13
  stageCode: string; // "STAGE-01" to "STAGE-13"
  name: string;
  proposedOwnerRole: string;
  completionOutputOrEvidence: string;
}

export interface InstantiatedActivity extends StageActivityDefinition {
  instanceId: string;
  projectId: string;
  status: ActivityStatus;
  actualOwner?: string;
  completedAt?: string;
  evidenceUri?: string;
  notes?: string;
}

export const ALL_STAGE_ACTIVITIES: StageActivityDefinition[] = [
  {
    id: "S01-01",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Capture title and project overview",
    proposedOwnerRole: "Intake owner",
    completionOutputOrEvidence: "Saved project with stable ID.",
  },
  {
    id: "S01-02",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Record origin and original source",
    proposedOwnerRole: "Intake owner",
    completionOutputOrEvidence: "Source reference or idea author.",
  },
  {
    id: "S01-03",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Select business route",
    proposedOwnerRole: "PM/intake owner",
    completionOutputOrEvidence: "Route classification.",
  },
  {
    id: "S01-04",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Select event format and operating model",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Editable template selection.",
  },
  {
    id: "S01-05",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Select commercial model",
    proposedOwnerRole: "Commercial lead",
    completionOutputOrEvidence: "Assumed or confirmed commercial model.",
  },
  {
    id: "S01-06",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Check duplicate or related projects",
    proposedOwnerRole: "Intake owner",
    completionOutputOrEvidence: "Linked existing record or duplicate decision.",
  },
  {
    id: "S01-07",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Link programme or parent agreement",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Parent relationship and inherited-term selection.",
  },
  {
    id: "S01-08",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Create or link client and billing party",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Verified party record or explicit internal/no-client state.",
  },
  {
    id: "S01-09",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Capture client description and objectives",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Brief summary with source.",
  },
  {
    id: "S01-10",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Identify client contacts and decision authority",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Contact list with authority status.",
  },
  {
    id: "S01-11",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Assign accountable PM and sponsor",
    proposedOwnerRole: "Management",
    completionOutputOrEvidence: "Named owner and sponsor role assignment.",
  },
  {
    id: "S01-12",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Assign initial department leads",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Responsibility map with vacancies visible.",
  },
  {
    id: "S01-13",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Record scope, exclusions and assumptions",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Initial scope register.",
  },
  {
    id: "S01-14",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Upload tender/brief/reference documents",
    proposedOwnerRole: "Document controller",
    completionOutputOrEvidence: "Indexed files and source versions.",
  },
  {
    id: "S01-15",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Capture submission date, time and timezone",
    proposedOwnerRole: "Bid lead",
    completionOutputOrEvidence: "Sourced deadline or confirmation task.",
  },
  {
    id: "S01-16",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Capture clarification and decision deadlines",
    proposedOwnerRole: "Bid lead/PM",
    completionOutputOrEvidence: "Deadline register with owners.",
  },
  {
    id: "S01-17",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Capture venue, location and access assumptions",
    proposedOwnerRole: "Logistics/PM",
    completionOutputOrEvidence: "Venue record and confidence status.",
  },
  {
    id: "S01-18",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Capture event sessions and duration basis",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Tentative/confirmed date windows.",
  },
  {
    id: "S01-19",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Record expected revenue/value and currency",
    proposedOwnerRole: "Commercial lead",
    completionOutputOrEvidence: "Valuation range or amount with basis.",
  },
  {
    id: "S01-20",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Record estimated cost and development allowance",
    proposedOwnerRole: "Finance/PM",
    completionOutputOrEvidence: "Cost assumptions and spending-authority gap.",
  },
  {
    id: "S01-21",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Select country/entity/venue policy overlays",
    proposedOwnerRole: "PM/admin",
    completionOutputOrEvidence: "Applicable-pack selection and review gaps.",
  },
  {
    id: "S01-22",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Set access, confidentiality and client visibility",
    proposedOwnerRole: "PM/admin",
    completionOutputOrEvidence: "Project permission profile.",
  },
  {
    id: "S01-23",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Select workflow, approvals and report template",
    proposedOwnerRole: "PM/admin",
    completionOutputOrEvidence: "Pinned configuration draft and overrides.",
  },
  {
    id: "S01-24",
    stageNumber: 1,
    stageCode: "STAGE-01",
    name: "Review onboarding gaps and activate next work",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Accepted intake or reasoned hold.",
  },
  {
    id: "S02-01",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Review brief and tender scope",
    proposedOwnerRole: "PM/bid lead",
    completionOutputOrEvidence: "Interpreted scope with source references.",
  },
  {
    id: "S02-02",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Extract mandatory deliverables",
    proposedOwnerRole: "Bid lead",
    completionOutputOrEvidence: "Requirement register with verification status.",
  },
  {
    id: "S02-03",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Check submission and participation conditions",
    proposedOwnerRole: "Bid lead",
    completionOutputOrEvidence: "Eligibility checklist and gaps.",
  },
  {
    id: "S02-04",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Review commercial terms and payment exposure",
    proposedOwnerRole: "Commercial/finance",
    completionOutputOrEvidence: "Reviewed exposure notes.",
  },
  {
    id: "S02-05",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Identify penalties, guarantees and liabilities",
    proposedOwnerRole: "Commercial reviewer",
    completionOutputOrEvidence: "Flagged clauses and review ownership.",
  },
  {
    id: "S02-06",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Check strategic fit and audience/client value",
    proposedOwnerRole: "Sponsor",
    completionOutputOrEvidence: "Opportunity rationale.",
  },
  {
    id: "S02-07",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Evaluate internal delivery capacity",
    proposedOwnerRole: "Operations lead",
    completionOutputOrEvidence: "Capacity summary across projects.",
  },
  {
    id: "S02-08",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Review design and workshop capacity",
    proposedOwnerRole: "Design/production leads",
    completionOutputOrEvidence: "Availability assumptions and pinch points.",
  },
  {
    id: "S02-09",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Review potential venue and access feasibility",
    proposedOwnerRole: "Logistics/technical",
    completionOutputOrEvidence: "Site feasibility notes.",
  },
  {
    id: "S02-10",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Identify permits and jurisdictional questions",
    proposedOwnerRole: "Compliance lead",
    completionOutputOrEvidence: "Applicability questions, not assumed clearance.",
  },
  {
    id: "S02-11",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Check resource and specialist availability",
    proposedOwnerRole: "Resource planner",
    completionOutputOrEvidence: "Tentative supply/capacity evidence.",
  },
  {
    id: "S02-12",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Assess project schedule realism",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Milestone feasibility and critical assumptions.",
  },
  {
    id: "S02-13",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Create initial cost range",
    proposedOwnerRole: "Estimator",
    completionOutputOrEvidence: "Cost range with inclusions and confidence.",
  },
  {
    id: "S02-14",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Create revenue/funding scenarios",
    proposedOwnerRole: "Commercial lead",
    completionOutputOrEvidence: "Assumed and supported revenue scenarios.",
  },
  {
    id: "S02-15",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Review cash requirements",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Timing of outflows/inflows and funding gap.",
  },
  {
    id: "S02-16",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Identify partners and rights obligations",
    proposedOwnerRole: "Commercial/IP lead",
    completionOutputOrEvidence: "Partner/licence needs and sources.",
  },
  {
    id: "S02-17",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Record safety and operational risks",
    proposedOwnerRole: "HSE/operations",
    completionOutputOrEvidence: "Initial risk register.",
  },
  {
    id: "S02-18",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Record logistics and cross-border risks",
    proposedOwnerRole: "Logistics lead",
    completionOutputOrEvidence: "Mobility/import questions where applicable.",
  },
  {
    id: "S02-19",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "List information needed from client/venue",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Clarification request draft.",
  },
  {
    id: "S02-20",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Compare delivery or concept alternatives",
    proposedOwnerRole: "PM/design",
    completionOutputOrEvidence: "Option matrix with assumptions.",
  },
  {
    id: "S02-21",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Estimate bid/development effort",
    proposedOwnerRole: "PM/finance",
    completionOutputOrEvidence: "Effort and development-spend request.",
  },
  {
    id: "S02-22",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Assign risk owners and review dates",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Owned mitigations and unknowns.",
  },
  {
    id: "S02-23",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Review pursue/hold/decline recommendation",
    proposedOwnerRole: "Sponsor/management",
    completionOutputOrEvidence: "Recorded decision and conditions.",
  },
  {
    id: "S02-24",
    stageNumber: 2,
    stageCode: "STAGE-02",
    name: "Update portfolio and release authorised next work",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Maturity change and authorised scope of development.",
  },
  {
    id: "S03-01",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Confirm creative objectives and success measures",
    proposedOwnerRole: "Design lead",
    completionOutputOrEvidence: "Approved or assumed creative brief.",
  },
  {
    id: "S03-02",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Identify audience and user journeys",
    proposedOwnerRole: "Experience designer",
    completionOutputOrEvidence: "Audience/flow assumptions.",
  },
  {
    id: "S03-03",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Confirm brand and IP constraints",
    proposedOwnerRole: "Brand/IP lead",
    completionOutputOrEvidence: "Sourced brand/rights checklist.",
  },
  {
    id: "S03-04",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Collect reference imagery and inspiration",
    proposedOwnerRole: "Design team",
    completionOutputOrEvidence: "Indexed references with usage notes.",
  },
  {
    id: "S03-05",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Develop creative themes and narratives",
    proposedOwnerRole: "Creative lead",
    completionOutputOrEvidence: "Distinct concept options.",
  },
  {
    id: "S03-06",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Create moodboards",
    proposedOwnerRole: "Design team",
    completionOutputOrEvidence: "Versioned moodboard packages.",
  },
  {
    id: "S03-07",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Define event zones and experiences",
    proposedOwnerRole: "Experience/operations",
    completionOutputOrEvidence: "Zone schedule and intended functions.",
  },
  {
    id: "S03-08",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Review accessibility and inclusive-use needs",
    proposedOwnerRole: "Design/operations",
    completionOutputOrEvidence: "Design considerations for review.",
  },
  {
    id: "S03-09",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Develop initial spatial layout",
    proposedOwnerRole: "Spatial designer",
    completionOutputOrEvidence: "First-draft layout with assumptions.",
  },
  {
    id: "S03-10",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Identify main structures and decor elements",
    proposedOwnerRole: "Design/production",
    completionOutputOrEvidence: "Element list linked to packages.",
  },
  {
    id: "S03-11",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Sketch audience and operational circulation",
    proposedOwnerRole: "Design/operations",
    completionOutputOrEvidence: "Flow plan and unresolved questions.",
  },
  {
    id: "S03-12",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Outline stage, AV and content experience",
    proposedOwnerRole: "Technical/creative",
    completionOutputOrEvidence: "Initial technical/creative concept.",
  },
  {
    id: "S03-13",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Identify interaction and activity requirements",
    proposedOwnerRole: "Experience team",
    completionOutputOrEvidence: "Activity descriptions and delivery needs.",
  },
  {
    id: "S03-14",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Select preliminary materials and methods",
    proposedOwnerRole: "Design/production",
    completionOutputOrEvidence: "Assumed build approach.",
  },
  {
    id: "S03-15",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Check venue fit against known information",
    proposedOwnerRole: "Technical lead",
    completionOutputOrEvidence: "Fit review and survey gaps.",
  },
  {
    id: "S03-16",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Prepare preliminary quantities",
    proposedOwnerRole: "Estimator/design",
    completionOutputOrEvidence: "Early quantity takeoff with confidence.",
  },
  {
    id: "S03-17",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Prepare option-level cost ranges",
    proposedOwnerRole: "Estimator",
    completionOutputOrEvidence: "Comparable option budgets.",
  },
  {
    id: "S03-18",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Review operational complexity",
    proposedOwnerRole: "Operations lead",
    completionOutputOrEvidence: "Staffing/throughput/maintenance concerns.",
  },
  {
    id: "S03-19",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Review early safety and technical concerns",
    proposedOwnerRole: "HSE/technical",
    completionOutputOrEvidence: "Review comments and action owners.",
  },
  {
    id: "S03-20",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Prepare first-draft presentation",
    proposedOwnerRole: "Design team",
    completionOutputOrEvidence: "Versioned internal review pack.",
  },
  {
    id: "S03-21",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Conduct internal concept review",
    proposedOwnerRole: "Configured reviewers",
    completionOutputOrEvidence: "Decisions by option/version.",
  },
  {
    id: "S03-22",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Publish selected concepts for client review",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Authorised client-visible versions.",
  },
  {
    id: "S03-23",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Record feedback and preferred direction",
    proposedOwnerRole: "Design/client coordinator",
    completionOutputOrEvidence: "Consolidated comments and selection.",
  },
  {
    id: "S03-24",
    stageNumber: 3,
    stageCode: "STAGE-03",
    name: "Release next design brief or concept deliverable",
    proposedOwnerRole: "Design lead/PM",
    completionOutputOrEvidence: "Purpose-specific release and outstanding assumptions.",
  },
  {
    id: "S04-01",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Consolidate technical and scope questions",
    proposedOwnerRole: "PM/design lead",
    completionOutputOrEvidence: "Clarification register.",
  },
  {
    id: "S04-02",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Assign each question to the correct respondent",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Responsible party and due date.",
  },
  {
    id: "S04-03",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Issue authorised clarification requests",
    proposedOwnerRole: "Bid/client coordinator",
    completionOutputOrEvidence: "Issued version and delivery evidence.",
  },
  {
    id: "S04-04",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Record responses and source authority",
    proposedOwnerRole: "Document controller",
    completionOutputOrEvidence: "Response/version with attribution.",
  },
  {
    id: "S04-05",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Assess response effects on scope and cost",
    proposedOwnerRole: "PM/estimator",
    completionOutputOrEvidence: "Impact links and actions.",
  },
  {
    id: "S04-06",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Plan and carry out venue/site survey",
    proposedOwnerRole: "Technical/logistics",
    completionOutputOrEvidence: "Survey record and limitations.",
  },
  {
    id: "S04-07",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Verify dimensions and existing services",
    proposedOwnerRole: "Technical lead",
    completionOutputOrEvidence: "Checked drawings/data or open gaps.",
  },
  {
    id: "S04-08",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Develop detailed layouts and zones",
    proposedOwnerRole: "Spatial designer",
    completionOutputOrEvidence: "Versioned technical layout.",
  },
  {
    id: "S04-09",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Develop structure and fabrication details",
    proposedOwnerRole: "Design/production",
    completionOutputOrEvidence: "Build-detail package.",
  },
  {
    id: "S04-10",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Develop AV, power and lighting requirements",
    proposedOwnerRole: "Technical lead",
    completionOutputOrEvidence: "Technical schedule and interfaces.",
  },
  {
    id: "S04-11",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Develop graphic/artwork specifications",
    proposedOwnerRole: "Design team",
    completionOutputOrEvidence: "Artwork sizes, finishes and versions.",
  },
  {
    id: "S04-12",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Coordinate access and operational circulation",
    proposedOwnerRole: "Operations/design",
    completionOutputOrEvidence: "Reviewed flow/clearance assumptions.",
  },
  {
    id: "S04-13",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Obtain specialist engineering input where applicable",
    proposedOwnerRole: "Technical lead",
    completionOutputOrEvidence: "Specialist deliverables and reviewer status.",
  },
  {
    id: "S04-14",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Coordinate venue, contractor and partner interfaces",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Interface responsibility register.",
  },
  {
    id: "S04-15",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Review local permit/document requirements",
    proposedOwnerRole: "Compliance lead",
    completionOutputOrEvidence: "Applicable submission list and owners.",
  },
  {
    id: "S04-16",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Update quantities and material takeoffs",
    proposedOwnerRole: "Estimator",
    completionOutputOrEvidence: "Version-linked takeoff.",
  },
  {
    id: "S04-17",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Update cost and programme impact",
    proposedOwnerRole: "Finance/PM",
    completionOutputOrEvidence: "Revised forecast and change exposure.",
  },
  {
    id: "S04-18",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Prepare technical approval sheets",
    proposedOwnerRole: "Design controller",
    completionOutputOrEvidence: "Purpose-specific issue package.",
  },
  {
    id: "S04-19",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Conduct internal interdisciplinary review",
    proposedOwnerRole: "Configured reviewers",
    completionOutputOrEvidence: "Comment register and dispositions.",
  },
  {
    id: "S04-20",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Publish authorised client/venue submissions",
    proposedOwnerRole: "Document controller",
    completionOutputOrEvidence: "Issued version and recipients.",
  },
  {
    id: "S04-21",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Resolve comments and revise drawings",
    proposedOwnerRole: "Design lead",
    completionOutputOrEvidence: "Revision record and closed/open comments.",
  },
  {
    id: "S04-22",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Approve packages for defined downstream use",
    proposedOwnerRole: "Authorised reviewers",
    completionOutputOrEvidence: "Release record by package/version.",
  },
  {
    id: "S04-23",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Withdraw or mark superseded site documents",
    proposedOwnerRole: "Document controller",
    completionOutputOrEvidence: "Controlled distribution update.",
  },
  {
    id: "S04-24",
    stageNumber: 4,
    stageCode: "STAGE-04",
    name: "Handover design requirements to costing/planning/build",
    proposedOwnerRole: "Design/PM",
    completionOutputOrEvidence: "Released data plus unresolved interface list.",
  },
  {
    id: "S05-01",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Confirm priced scope and exclusions",
    proposedOwnerRole: "Commercial/PM",
    completionOutputOrEvidence: "Controlled commercial scope.",
  },
  {
    id: "S05-02",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Create BOQ structure linked to packages",
    proposedOwnerRole: "Estimator",
    completionOutputOrEvidence: "BOQ hierarchy and traceability.",
  },
  {
    id: "S05-03",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Define quantities and meaningful units",
    proposedOwnerRole: "Estimator",
    completionOutputOrEvidence: "Quantity/unit basis.",
  },
  {
    id: "S05-04",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Build material, labour, plant and subcontract costs",
    proposedOwnerRole: "Estimator",
    completionOutputOrEvidence: "Internal cost components.",
  },
  {
    id: "S05-05",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Include transport, logistics and operating costs",
    proposedOwnerRole: "PM/estimator",
    completionOutputOrEvidence: "Complete cost assumptions.",
  },
  {
    id: "S05-06",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Review overhead and contingency basis",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Disclosed allocation and contingency model.",
  },
  {
    id: "S05-07",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Create selling prices and commercial options",
    proposedOwnerRole: "Commercial lead",
    completionOutputOrEvidence: "Client-facing pricing version.",
  },
  {
    id: "S05-08",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Check margin versus markup definitions",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Correctly labelled calculations.",
  },
  {
    id: "S05-09",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Review currency, FX and local finance treatment",
    proposedOwnerRole: "Finance/local reviewer",
    completionOutputOrEvidence: "Approved assumptions or review gaps.",
  },
  {
    id: "S05-10",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Model payment milestones and cash requirements",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Contract-specific cash forecast.",
  },
  {
    id: "S05-11",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Check tender returnables and formatting",
    proposedOwnerRole: "Bid lead",
    completionOutputOrEvidence: "Submission compliance register.",
  },
  {
    id: "S05-12",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Separate technical and commercial packs",
    proposedOwnerRole: "Bid/document controller",
    completionOutputOrEvidence: "Correctly segregated issue files.",
  },
  {
    id: "S05-13",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Review guarantees, insurance and liability terms",
    proposedOwnerRole: "Commercial reviewer",
    completionOutputOrEvidence: "Authority decision on exposure.",
  },
  {
    id: "S05-14",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Obtain internal quotation/submission approval",
    proposedOwnerRole: "Configured approvers",
    completionOutputOrEvidence: "Version-bound authorisation.",
  },
  {
    id: "S05-15",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Publish or issue proposal to authorised recipients",
    proposedOwnerRole: "Client/bid coordinator",
    completionOutputOrEvidence: "Actual issue evidence.",
  },
  {
    id: "S05-16",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Record submission date/time and receipt",
    proposedOwnerRole: "Bid lead",
    completionOutputOrEvidence: "Portal/email receipt with timezone.",
  },
  {
    id: "S05-17",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Track client clarification and negotiation",
    proposedOwnerRole: "Commercial/PM",
    completionOutputOrEvidence: "Negotiation log and actions.",
  },
  {
    id: "S05-18",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Control resubmitted versions and validity",
    proposedOwnerRole: "Document controller",
    completionOutputOrEvidence: "Revised offer/version history.",
  },
  {
    id: "S05-19",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Record award, loss, withdrawal or hold",
    proposedOwnerRole: "Sponsor/commercial",
    completionOutputOrEvidence: "Actual decision evidence.",
  },
  {
    id: "S05-20",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Review signed contract or internal investment authority",
    proposedOwnerRole: "Commercial/management",
    completionOutputOrEvidence: "Accepted authority and scope.",
  },
  {
    id: "S05-21",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Reconcile awarded scope against submitted scope",
    proposedOwnerRole: "PM/finance",
    completionOutputOrEvidence: "Difference register and baseline changes.",
  },
  {
    id: "S05-22",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Approve delivery budget and revenue baseline",
    proposedOwnerRole: "Finance/management",
    completionOutputOrEvidence: "Authorised baseline version.",
  },
  {
    id: "S05-23",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Set billing, claims and client-change rules",
    proposedOwnerRole: "Finance/PM",
    completionOutputOrEvidence: "Contract-specific commercial controls.",
  },
  {
    id: "S05-24",
    stageNumber: 5,
    stageCode: "STAGE-05",
    name: "Release authorised delivery work and retain bid learning",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Handover package or bid closeout record.",
  },
  {
    id: "S06-01",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Confirm authorised scope and current assumptions",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Agreed planning basis.",
  },
  {
    id: "S06-02",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Build zones, workstreams and packages",
    proposedOwnerRole: "PM/department leads",
    completionOutputOrEvidence: "Work breakdown structure.",
  },
  {
    id: "S06-03",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Map requirements to packages",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Scope-coverage register.",
  },
  {
    id: "S06-04",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Assign package owners and reviewers",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Responsibility matrix.",
  },
  {
    id: "S06-05",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Define acceptance criteria and evidence",
    proposedOwnerRole: "Package owners/quality",
    completionOutputOrEvidence: "Measurable acceptance plans.",
  },
  {
    id: "S06-06",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Create project and location calendars",
    proposedOwnerRole: "Planner/admin",
    completionOutputOrEvidence: "Reviewed calendars and timezone settings.",
  },
  {
    id: "S06-07",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Set fixed and relative milestones",
    proposedOwnerRole: "Planner",
    completionOutputOrEvidence: "Sourced milestone register.",
  },
  {
    id: "S06-08",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Sequence tasks and dependencies",
    proposedOwnerRole: "Planner/leads",
    completionOutputOrEvidence: "Dependency network.",
  },
  {
    id: "S06-09",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Estimate durations with confidence",
    proposedOwnerRole: "Package leads",
    completionOutputOrEvidence: "Duration basis and uncertainty.",
  },
  {
    id: "S06-10",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Create approved baseline and forecast view",
    proposedOwnerRole: "Planner/PM",
    completionOutputOrEvidence: "Separate schedule versions.",
  },
  {
    id: "S06-11",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Plan design releases by package",
    proposedOwnerRole: "Design/planner",
    completionOutputOrEvidence: "Release dates and interfaces.",
  },
  {
    id: "S06-12",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Build procurement schedule and lead times",
    proposedOwnerRole: "Procurement/planner",
    completionOutputOrEvidence: "RFQ/order/receipt targets.",
  },
  {
    id: "S06-13",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Reserve tentative crew and equipment demand",
    proposedOwnerRole: "Resource planner",
    completionOutputOrEvidence: "Demand profile and clashes.",
  },
  {
    id: "S06-14",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Plan workshop and fabrication capacity",
    proposedOwnerRole: "Production planner",
    completionOutputOrEvidence: "Workshop load plan.",
  },
  {
    id: "S06-15",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Plan transport, storage and venue access",
    proposedOwnerRole: "Logistics lead",
    completionOutputOrEvidence: "Mobilisation strategy.",
  },
  {
    id: "S06-16",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Define staffing, training and welfare needs",
    proposedOwnerRole: "Operations/HR",
    completionOutputOrEvidence: "Role and deployment plan.",
  },
  {
    id: "S06-17",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Prepare risk, method and emergency planning needs",
    proposedOwnerRole: "HSE/operations",
    completionOutputOrEvidence: "Document/task register with applicability.",
  },
  {
    id: "S06-18",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Plan permits, licences and certificates",
    proposedOwnerRole: "Compliance lead",
    completionOutputOrEvidence: "Obligation deadlines and reviewers.",
  },
  {
    id: "S06-19",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Define quality checks and opening criteria",
    proposedOwnerRole: "Quality/technical",
    completionOutputOrEvidence: "Inspection/readiness plan.",
  },
  {
    id: "S06-20",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Define client reporting and meeting cadence",
    proposedOwnerRole: "Client coordinator/PM",
    completionOutputOrEvidence: "Communication plan.",
  },
  {
    id: "S06-21",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Define KPI sources and evidence capture",
    proposedOwnerRole: "Reporting lead",
    completionOutputOrEvidence: "Measurement/data plan.",
  },
  {
    id: "S06-22",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Set change, escalation and exception routes",
    proposedOwnerRole: "PM/admin",
    completionOutputOrEvidence: "Project-specific control configuration.",
  },
  {
    id: "S06-23",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Review cross-project conflicts and contingency",
    proposedOwnerRole: "PM/management",
    completionOutputOrEvidence: "Recovery/contingency actions.",
  },
  {
    id: "S06-24",
    stageNumber: 6,
    stageCode: "STAGE-06",
    name: "Approve and communicate delivery baseline",
    proposedOwnerRole: "Configured approvers/PM",
    completionOutputOrEvidence: "Released plan and assigned work.",
  },
  {
    id: "S07-01",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Identify goods/services and package allocation",
    proposedOwnerRole: "Package owner",
    completionOutputOrEvidence: "Requisition with scope links.",
  },
  {
    id: "S07-02",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Confirm current technical specification",
    proposedOwnerRole: "Technical/package lead",
    completionOutputOrEvidence: "Released specification or explicit limitation.",
  },
  {
    id: "S07-03",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Confirm quantity, unit and delivery location",
    proposedOwnerRole: "Procurement/package owner",
    completionOutputOrEvidence: "Purchasable line definition.",
  },
  {
    id: "S07-04",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Check budget authority and available allocation",
    proposedOwnerRole: "Finance/procurement",
    completionOutputOrEvidence: "Authorised budget position.",
  },
  {
    id: "S07-05",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Select sourcing method",
    proposedOwnerRole: "Procurement lead",
    completionOutputOrEvidence: "Competition/agreement/sole-source decision.",
  },
  {
    id: "S07-06",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Identify suitable vendors",
    proposedOwnerRole: "Procurement",
    completionOutputOrEvidence: "Vendor shortlist and basis.",
  },
  {
    id: "S07-07",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Collect vendor onboarding and local documents",
    proposedOwnerRole: "Procurement/compliance",
    completionOutputOrEvidence: "Reviewed vendor record and gaps.",
  },
  {
    id: "S07-08",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Issue controlled RFQ packages",
    proposedOwnerRole: "Procurement",
    completionOutputOrEvidence: "RFQ version and recipient list.",
  },
  {
    id: "S07-09",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Record vendor questions and shared clarifications",
    proposedOwnerRole: "Procurement/technical",
    completionOutputOrEvidence: "Clarification history.",
  },
  {
    id: "S07-10",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Receive offers with validity and exceptions",
    proposedOwnerRole: "Procurement",
    completionOutputOrEvidence: "Versioned offers and terms.",
  },
  {
    id: "S07-11",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Review technical conformity",
    proposedOwnerRole: "Technical evaluator",
    completionOutputOrEvidence: "Conformity assessment.",
  },
  {
    id: "S07-12",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Compare total delivered costs and exclusions",
    proposedOwnerRole: "Procurement/finance",
    completionOutputOrEvidence: "Comparable cost analysis.",
  },
  {
    id: "S07-13",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Evaluate lead time, capacity and service risks",
    proposedOwnerRole: "Procurement/operations",
    completionOutputOrEvidence: "Delivery-risk assessment.",
  },
  {
    id: "S07-14",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Record selection and negotiation outcome",
    proposedOwnerRole: "Procurement lead",
    completionOutputOrEvidence: "Selection memo and offer version.",
  },
  {
    id: "S07-15",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Obtain purchase/commitment authorisation",
    proposedOwnerRole: "Configured approvers",
    completionOutputOrEvidence: "Authority linked to scope/value.",
  },
  {
    id: "S07-16",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Create PO or subcontract with correct terms",
    proposedOwnerRole: "Procurement",
    completionOutputOrEvidence: "Controlled order/contract draft.",
  },
  {
    id: "S07-17",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Issue order and confirm actual supplier receipt",
    proposedOwnerRole: "Procurement",
    completionOutputOrEvidence: "Issued document and receipt evidence.",
  },
  {
    id: "S07-18",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Obtain supplier acknowledgement",
    proposedOwnerRole: "Procurement",
    completionOutputOrEvidence: "Confirmed dates/specifications or discrepancies.",
  },
  {
    id: "S07-19",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Schedule delivery, inspection and payment milestones",
    proposedOwnerRole: "Procurement/finance",
    completionOutputOrEvidence: "Owned milestone plan.",
  },
  {
    id: "S07-20",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Track production and promised delivery",
    proposedOwnerRole: "Procurement/package lead",
    completionOutputOrEvidence: "Supplier progress and forecast.",
  },
  {
    id: "S07-21",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Control amendments and substitutions",
    proposedOwnerRole: "Procurement/technical",
    completionOutputOrEvidence: "Approved change/version.",
  },
  {
    id: "S07-22",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Record cancellation, expediting or alternate sourcing",
    proposedOwnerRole: "Procurement lead",
    completionOutputOrEvidence: "Decision and commercial impact.",
  },
  {
    id: "S07-23",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Link receipts/invoices to commitments",
    proposedOwnerRole: "Finance/procurement",
    completionOutputOrEvidence: "Matching and unresolved discrepancies.",
  },
  {
    id: "S07-24",
    stageNumber: 7,
    stageCode: "STAGE-07",
    name: "Handover confirmed supplier scope to delivery teams",
    proposedOwnerRole: "Procurement/PM",
    completionOutputOrEvidence: "Authoritative order and contact package.",
  },
  {
    id: "S08-01",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Confirm fabrication/service release authority",
    proposedOwnerRole: "Production lead",
    completionOutputOrEvidence: "Purpose-specific authorised work package.",
  },
  {
    id: "S08-02",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Check drawings and specifications in use",
    proposedOwnerRole: "Production/design controller",
    completionOutputOrEvidence: "Correct version at workstations.",
  },
  {
    id: "S08-03",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Create material requirements and work orders",
    proposedOwnerRole: "Production planner",
    completionOutputOrEvidence: "Version-linked material/work plan.",
  },
  {
    id: "S08-04",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Allocate workshop operations and labour",
    proposedOwnerRole: "Production planner",
    completionOutputOrEvidence: "Capacity-based schedule.",
  },
  {
    id: "S08-05",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Reserve owned or rented equipment",
    proposedOwnerRole: "Resource planner",
    completionOutputOrEvidence: "Confirmed/tentative reservation records.",
  },
  {
    id: "S08-06",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Resolve shortages and subrental needs",
    proposedOwnerRole: "Procurement/resource planner",
    completionOutputOrEvidence: "Approved substitution or supply plan.",
  },
  {
    id: "S08-07",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Receive and inspect materials",
    proposedOwnerRole: "Stores/quality",
    completionOutputOrEvidence: "Receipt and acceptance/discrepancy.",
  },
  {
    id: "S08-08",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Issue materials to work packages",
    proposedOwnerRole: "Stores",
    completionOutputOrEvidence: "Traceable material movement.",
  },
  {
    id: "S08-09",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Fabricate structures and scenic elements",
    proposedOwnerRole: "Fabrication lead",
    completionOutputOrEvidence: "Recorded production progress.",
  },
  {
    id: "S08-10",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Produce graphics, finishes and branding",
    proposedOwnerRole: "Graphics/production",
    completionOutputOrEvidence: "Version-correct finished items.",
  },
  {
    id: "S08-11",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Create and test AV/media content",
    proposedOwnerRole: "Content/technical",
    completionOutputOrEvidence: "Tested deliverable versions.",
  },
  {
    id: "S08-12",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Track outsourced production milestones",
    proposedOwnerRole: "Procurement/production",
    completionOutputOrEvidence: "Supplier progress evidence.",
  },
  {
    id: "S08-13",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Conduct in-process inspections",
    proposedOwnerRole: "Quality lead",
    completionOutputOrEvidence: "Inspection results and corrective work.",
  },
  {
    id: "S08-14",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Record defects, rework and material waste",
    proposedOwnerRole: "Production/quality",
    completionOutputOrEvidence: "Nonconformance and cost impact.",
  },
  {
    id: "S08-15",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Control technical/material substitutions",
    proposedOwnerRole: "Design/technical",
    completionOutputOrEvidence: "Accepted alternate and change basis.",
  },
  {
    id: "S08-16",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Test electrical/mechanical/technical assemblies",
    proposedOwnerRole: "Competent technical team",
    completionOutputOrEvidence: "Applicable test evidence and reviewer.",
  },
  {
    id: "S08-17",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Prepare maintenance and condition checks",
    proposedOwnerRole: "Asset/technical lead",
    completionOutputOrEvidence: "Resource readiness status.",
  },
  {
    id: "S08-18",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Confirm crew assignments and availability",
    proposedOwnerRole: "Operations/HR",
    completionOutputOrEvidence: "Accepted assignments and gaps.",
  },
  {
    id: "S08-19",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Check qualifications and project access requirements",
    proposedOwnerRole: "HR/compliance",
    completionOutputOrEvidence: "Reviewed validity/applicability records.",
  },
  {
    id: "S08-20",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Prepare training, induction and instructions",
    proposedOwnerRole: "Operations/HSE",
    completionOutputOrEvidence: "Training materials and attendance plan.",
  },
  {
    id: "S08-21",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Create packing lists and asset labels",
    proposedOwnerRole: "Logistics/stores",
    completionOutputOrEvidence: "Package-level dispatch list.",
  },
  {
    id: "S08-22",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Verify spare parts, tools and consumables",
    proposedOwnerRole: "Technical/logistics",
    completionOutputOrEvidence: "Readiness checklist.",
  },
  {
    id: "S08-23",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Accept completed packages for dispatch",
    proposedOwnerRole: "Quality/package owner",
    completionOutputOrEvidence: "Accepted output or partial release.",
  },
  {
    id: "S08-24",
    stageNumber: 8,
    stageCode: "STAGE-08",
    name: "Update actual effort/cost and mobilisation forecast",
    proposedOwnerRole: "Production/finance",
    completionOutputOrEvidence: "Production status, exposure and handover.",
  },
  {
    id: "S09-01",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Confirm venue access windows and restrictions",
    proposedOwnerRole: "Logistics/venue liaison",
    completionOutputOrEvidence: "Actual access confirmation and conditions.",
  },
  {
    id: "S09-02",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Confirm logistics scope and approved allowance",
    proposedOwnerRole: "Logistics/finance",
    completionOutputOrEvidence: "Authorised transport/build budget.",
  },
  {
    id: "S09-03",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Create load, vehicle and trip plan",
    proposedOwnerRole: "Logistics lead",
    completionOutputOrEvidence: "Load lists and schedule.",
  },
  {
    id: "S09-04",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Coordinate delivery slots with venue and vendors",
    proposedOwnerRole: "Logistics coordinator",
    completionOutputOrEvidence: "Confirmed slot register.",
  },
  {
    id: "S09-05",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Arrange cross-border documents where applicable",
    proposedOwnerRole: "Logistics/local specialist",
    completionOutputOrEvidence: "Reviewed movement documents and gaps.",
  },
  {
    id: "S09-06",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Confirm vehicle, driver and route requirements",
    proposedOwnerRole: "Logistics",
    completionOutputOrEvidence: "Assigned resources and conditions.",
  },
  {
    id: "S09-07",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Confirm crew transport, welfare and accommodation",
    proposedOwnerRole: "Logistics/HR",
    completionOutputOrEvidence: "Deployment arrangements.",
  },
  {
    id: "S09-08",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Prepare access passes and personnel lists",
    proposedOwnerRole: "Site coordinator",
    completionOutputOrEvidence: "Venue-accepted credentials where required.",
  },
  {
    id: "S09-09",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Verify dispatch readiness of each package",
    proposedOwnerRole: "Stores/quality",
    completionOutputOrEvidence: "Accepted or exception-labelled release.",
  },
  {
    id: "S09-10",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Scan/record dispatch and condition",
    proposedOwnerRole: "Stores/logistics",
    completionOutputOrEvidence: "Custody and outbound evidence.",
  },
  {
    id: "S09-11",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Track transport status and delays",
    proposedOwnerRole: "Logistics coordinator",
    completionOutputOrEvidence: "Actual journey updates.",
  },
  {
    id: "S09-12",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Receive loads and reconcile quantities",
    proposedOwnerRole: "Site stores",
    completionOutputOrEvidence: "Receipt, condition and discrepancies.",
  },
  {
    id: "S09-13",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Brief crews on venue rules and current instructions",
    proposedOwnerRole: "Site/HSE lead",
    completionOutputOrEvidence: "Briefing record and correct documents.",
  },
  {
    id: "S09-14",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Set out installation locations and references",
    proposedOwnerRole: "Technical/site lead",
    completionOutputOrEvidence: "Confirmed setting-out record.",
  },
  {
    id: "S09-15",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Install infrastructure and essential services",
    proposedOwnerRole: "Technical/site teams",
    completionOutputOrEvidence: "Installation evidence and dependencies.",
  },
  {
    id: "S09-16",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Install structures, staging and scenic packages",
    proposedOwnerRole: "Installation lead",
    completionOutputOrEvidence: "Package progress and technical issues.",
  },
  {
    id: "S09-17",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Install AV, lighting and content systems",
    proposedOwnerRole: "Technical teams",
    completionOutputOrEvidence: "Installed systems and test readiness.",
  },
  {
    id: "S09-18",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Install signage, branding and visitor features",
    proposedOwnerRole: "Installation/design",
    completionOutputOrEvidence: "Version-correct placement evidence.",
  },
  {
    id: "S09-19",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Coordinate shared access and work interfaces",
    proposedOwnerRole: "Site manager",
    completionOutputOrEvidence: "Interface decisions and updated sequence.",
  },
  {
    id: "S09-20",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Record site queries and scope deviations",
    proposedOwnerRole: "Site/PM",
    completionOutputOrEvidence: "Query/change requests with impact.",
  },
  {
    id: "S09-21",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Inspect installation and log snags",
    proposedOwnerRole: "Quality/technical",
    completionOutputOrEvidence: "Inspection and owned snag register.",
  },
  {
    id: "S09-22",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Update installation forecast and recovery actions",
    proposedOwnerRole: "Site/planner",
    completionOutputOrEvidence: "Actual progress and recovery plan.",
  },
  {
    id: "S09-23",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Record actual logistics usage and charges",
    proposedOwnerRole: "Logistics/finance",
    completionOutputOrEvidence: "Supported cost/variation records.",
  },
  {
    id: "S09-24",
    stageNumber: 9,
    stageCode: "STAGE-09",
    name: "Handover installed zones to finishing/testing",
    proposedOwnerRole: "Site/quality",
    completionOutputOrEvidence: "Zone status, open conditions and custody.",
  },
  {
    id: "S10-01",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Confirm readiness scope and responsible decision-makers",
    proposedOwnerRole: "PM/operations",
    completionOutputOrEvidence: "Scope-specific readiness plan.",
  },
  {
    id: "S10-02",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Inspect finishes, cleanliness and presentation",
    proposedOwnerRole: "Quality/design",
    completionOutputOrEvidence: "Accepted finishes and snags.",
  },
  {
    id: "S10-03",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Verify installed layout against approved versions",
    proposedOwnerRole: "Technical/design",
    completionOutputOrEvidence: "Conformity record and differences.",
  },
  {
    id: "S10-04",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Complete structural/specialist checks where applicable",
    proposedOwnerRole: "Qualified specialist/technical",
    completionOutputOrEvidence: "Actual accepted specialist evidence.",
  },
  {
    id: "S10-05",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Complete electrical and technical tests as applicable",
    proposedOwnerRole: "Competent technical team",
    completionOutputOrEvidence: "Test results and limitations.",
  },
  {
    id: "S10-06",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Test AV, lighting, playback and communication systems",
    proposedOwnerRole: "Technical lead",
    completionOutputOrEvidence: "Function test records.",
  },
  {
    id: "S10-07",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Test activity/equipment operating functions",
    proposedOwnerRole: "Operations/technical",
    completionOutputOrEvidence: "Accepted functional checks.",
  },
  {
    id: "S10-08",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Review accessibility and visitor circulation",
    proposedOwnerRole: "Operations/quality",
    completionOutputOrEvidence: "Reviewed access/flow conditions.",
  },
  {
    id: "S10-09",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Verify emergency routes and response arrangements",
    proposedOwnerRole: "HSE/venue liaison",
    completionOutputOrEvidence: "Reviewed actual conditions and open issues.",
  },
  {
    id: "S10-10",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Check security, medical and welfare readiness",
    proposedOwnerRole: "Operations/HSE",
    completionOutputOrEvidence: "Assigned service readiness evidence.",
  },
  {
    id: "S10-11",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Verify actual permit/licence/certificate status",
    proposedOwnerRole: "Compliance lead",
    completionOutputOrEvidence: "Validity/applicability register.",
  },
  {
    id: "S10-12",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Confirm insurance and specialist document conditions",
    proposedOwnerRole: "Compliance/commercial",
    completionOutputOrEvidence: "Reviewed requirements and gaps.",
  },
  {
    id: "S10-13",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Confirm crew attendance, briefings and competencies",
    proposedOwnerRole: "Operations/HR",
    completionOutputOrEvidence: "Deployment and briefing evidence.",
  },
  {
    id: "S10-14",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Test entry/ticketing processes where relevant",
    proposedOwnerRole: "Operations/IT",
    completionOutputOrEvidence: "Validated process and fallback test.",
  },
  {
    id: "S10-15",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Test connectivity, power contingency and communications",
    proposedOwnerRole: "Technical/IT",
    completionOutputOrEvidence: "Resilience test results.",
  },
  {
    id: "S10-16",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Conduct rehearsal or operational simulation",
    proposedOwnerRole: "Operations/show lead",
    completionOutputOrEvidence: "Rehearsal outcomes and actions.",
  },
  {
    id: "S10-17",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Classify snags by actual operational consequence",
    proposedOwnerRole: "Quality/technical",
    completionOutputOrEvidence: "Agreed criticality and owner.",
  },
  {
    id: "S10-18",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Close and retest corrected defects",
    proposedOwnerRole: "Responsible team/quality",
    completionOutputOrEvidence: "Accepted corrective evidence.",
  },
  {
    id: "S10-19",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Assess partial opening and shared dependencies",
    proposedOwnerRole: "PM/HSE/operations",
    completionOutputOrEvidence: "Scoped assessment and residual conditions.",
  },
  {
    id: "S10-20",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Obtain client/venue acceptance where required",
    proposedOwnerRole: "Client/venue coordinator",
    completionOutputOrEvidence: "Actual acceptance evidence.",
  },
  {
    id: "S10-21",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Prepare readiness decision pack",
    proposedOwnerRole: "PM/quality",
    completionOutputOrEvidence: "Sourced matrix and unresolved conditions.",
  },
  {
    id: "S10-22",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Record opening or hold decision",
    proposedOwnerRole: "Designated authority",
    completionOutputOrEvidence: "Attributable decision, scope and conditions.",
  },
  {
    id: "S10-23",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Publish operating instructions and constraints",
    proposedOwnerRole: "Operations",
    completionOutputOrEvidence: "Current authorised instructions.",
  },
  {
    id: "S10-24",
    stageNumber: 10,
    stageCode: "STAGE-10",
    name: "Handover to live command team",
    proposedOwnerRole: "Site/operations leads",
    completionOutputOrEvidence: "Accepted handover and follow-up owners.",
  },
  {
    id: "S11-01",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Activate the operating session or shift",
    proposedOwnerRole: "Operations lead",
    completionOutputOrEvidence: "Actual session/shift state and restrictions.",
  },
  {
    id: "S11-02",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Confirm opening conditions and unresolved actions",
    proposedOwnerRole: "Duty manager",
    completionOutputOrEvidence: "Shift awareness and action ownership.",
  },
  {
    id: "S11-03",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Brief and deploy crew and service providers",
    proposedOwnerRole: "Operations/HR",
    completionOutputOrEvidence: "Actual attendance and role coverage.",
  },
  {
    id: "S11-04",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Confirm run-of-show and client priorities",
    proposedOwnerRole: "Show/PM lead",
    completionOutputOrEvidence: "Current operational schedule.",
  },
  {
    id: "S11-05",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Complete opening/service checks",
    proposedOwnerRole: "Duty/technical teams",
    completionOutputOrEvidence: "Accepted daily check evidence.",
  },
  {
    id: "S11-06",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Monitor ticketing/entry and visitor flow where relevant",
    proposedOwnerRole: "Operations/entry lead",
    completionOutputOrEvidence: "Source-labelled entry/flow records.",
  },
  {
    id: "S11-07",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Monitor capacity and queue conditions where applicable",
    proposedOwnerRole: "Operations/security",
    completionOutputOrEvidence: "Observations and authorised response.",
  },
  {
    id: "S11-08",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Deliver programme, activities and contracted services",
    proposedOwnerRole: "Workstream leads",
    completionOutputOrEvidence: "Session/deliverable records.",
  },
  {
    id: "S11-09",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Maintain AV, equipment and essential systems",
    proposedOwnerRole: "Technical lead",
    completionOutputOrEvidence: "Maintenance and availability logs.",
  },
  {
    id: "S11-10",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Monitor cleaning, welfare, security and medical coverage",
    proposedOwnerRole: "Operations leads",
    completionOutputOrEvidence: "Service logs and gaps.",
  },
  {
    id: "S11-11",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Record incidents and immediate response",
    proposedOwnerRole: "Duty manager/HSE",
    completionOutputOrEvidence: "Restricted incident and actual action record.",
  },
  {
    id: "S11-12",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Escalate emergencies through the real response plan",
    proposedOwnerRole: "Designated responders",
    completionOutputOrEvidence: "Response actions and later reconciliation.",
  },
  {
    id: "S11-13",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Track downtime and service interruption",
    proposedOwnerRole: "Technical/operations",
    completionOutputOrEvidence: "Duration, cause and affected scope.",
  },
  {
    id: "S11-14",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Capture client requests and instructions",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Attributed request and scope assessment.",
  },
  {
    id: "S11-15",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Assess and authorise live changes",
    proposedOwnerRole: "PM/commercial",
    completionOutputOrEvidence: "Approved or provisional change decision.",
  },
  {
    id: "S11-16",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Record extra labour, materials and supplier usage",
    proposedOwnerRole: "Operations/finance",
    completionOutputOrEvidence: "Supported usage and cost exposure.",
  },
  {
    id: "S11-17",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Capture agreed attendance and performance data",
    proposedOwnerRole: "Reporting/operations",
    completionOutputOrEvidence: "Defined metrics with freshness/status.",
  },
  {
    id: "S11-18",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Capture sponsorship, rights and partner deliverables",
    proposedOwnerRole: "Partnership lead",
    completionOutputOrEvidence: "Delivery evidence against obligations.",
  },
  {
    id: "S11-19",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Capture approved photos/video and consent status",
    proposedOwnerRole: "Content team",
    completionOutputOrEvidence: "Classified assets and usage permissions.",
  },
  {
    id: "S11-20",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Collect client/visitor feedback appropriately",
    proposedOwnerRole: "Experience/reporting",
    completionOutputOrEvidence: "Source-labelled feedback and privacy controls.",
  },
  {
    id: "S11-21",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Prepare daily operational and client reports",
    proposedOwnerRole: "PM/reporting",
    completionOutputOrEvidence: "Reviewed audience-specific reports.",
  },
  {
    id: "S11-22",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Handover between shifts with unresolved issues",
    proposedOwnerRole: "Duty managers",
    completionOutputOrEvidence: "Accepted handover and ownership.",
  },
  {
    id: "S11-23",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Accept completed services and final event delivery",
    proposedOwnerRole: "PM/client coordinator",
    completionOutputOrEvidence: "Scope-specific acceptance evidence.",
  },
  {
    id: "S11-24",
    stageNumber: 11,
    stageCode: "STAGE-11",
    name: "Trigger next period or final closeout work",
    proposedOwnerRole: "PM/operations",
    completionOutputOrEvidence: "Defined transition and actual end anchors.",
  },
  {
    id: "S12-01",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Confirm actual event end and handback deadline",
    proposedOwnerRole: "PM/logistics",
    completionOutputOrEvidence: "Sourced actual end and agreed return window.",
  },
  {
    id: "S12-02",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Review bump-out scope, sequence and authority",
    proposedOwnerRole: "Logistics/PM",
    completionOutputOrEvidence: "Authorised dismantling plan.",
  },
  {
    id: "S12-03",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Confirm crew, vehicles, equipment and access",
    proposedOwnerRole: "Logistics/resource planner",
    completionOutputOrEvidence: "Bump-out deployment.",
  },
  {
    id: "S12-04",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Brief teams and control work interfaces",
    proposedOwnerRole: "Site/HSE lead",
    completionOutputOrEvidence: "Actual briefing and sequencing record.",
  },
  {
    id: "S12-05",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Dismantle systems and structures by plan",
    proposedOwnerRole: "Technical/installation teams",
    completionOutputOrEvidence: "Dismantling progress and issues.",
  },
  {
    id: "S12-06",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Record asset condition before removal",
    proposedOwnerRole: "Asset/quality team",
    completionOutputOrEvidence: "Condition evidence and discrepancies.",
  },
  {
    id: "S12-07",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Reconcile items against dispatch and site custody",
    proposedOwnerRole: "Stores/logistics",
    completionOutputOrEvidence: "Quantity/serial reconciliation.",
  },
  {
    id: "S12-08",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Pack and dispatch owned/rented assets",
    proposedOwnerRole: "Stores/logistics",
    completionOutputOrEvidence: "Return/transfer movement records.",
  },
  {
    id: "S12-09",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Receive warehouse returns and inspect condition",
    proposedOwnerRole: "Stores/technical",
    completionOutputOrEvidence: "Receipt and ready/quarantine status.",
  },
  {
    id: "S12-10",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Return subrentals and obtain acceptance",
    proposedOwnerRole: "Procurement/logistics",
    completionOutputOrEvidence: "Supplier return receipt and conditions.",
  },
  {
    id: "S12-11",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Transfer touring assets to next location where applicable",
    proposedOwnerRole: "Logistics",
    completionOutputOrEvidence: "Authorised transfer and next-project custody.",
  },
  {
    id: "S12-12",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Record loss, damage and repair requirements",
    proposedOwnerRole: "Asset/finance",
    completionOutputOrEvidence: "Claims and repair work orders.",
  },
  {
    id: "S12-13",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Complete cleaning, waste and reinstatement obligations",
    proposedOwnerRole: "Site/venue liaison",
    completionOutputOrEvidence: "Reinstatement evidence.",
  },
  {
    id: "S12-14",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Obtain venue handback acceptance",
    proposedOwnerRole: "PM/venue coordinator",
    completionOutputOrEvidence: "Actual acceptance or disputed items.",
  },
  {
    id: "S12-15",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Close crew attendance and approved usage",
    proposedOwnerRole: "Operations/HR",
    completionOutputOrEvidence: "Reviewed labour/service actuals.",
  },
  {
    id: "S12-16",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Collect final supplier invoices and expense evidence",
    proposedOwnerRole: "Procurement/finance",
    completionOutputOrEvidence: "Complete received documents and gaps.",
  },
  {
    id: "S12-17",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Match invoices to orders, receipts and variations",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Matched actuals and discrepancy queue.",
  },
  {
    id: "S12-18",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Record accruals for incurred but uninvoiced costs",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Supported accrual basis and reversal plan.",
  },
  {
    id: "S12-19",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Resolve open commitments and cancelled balances",
    proposedOwnerRole: "Procurement/finance",
    completionOutputOrEvidence: "Accurate remaining commitment position.",
  },
  {
    id: "S12-20",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Review approved/pending client variations and claims",
    proposedOwnerRole: "Commercial/PM",
    completionOutputOrEvidence: "Authorised value and separate exposure.",
  },
  {
    id: "S12-21",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Prepare billing and collection follow-up",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Issued/requested billing and receivable position.",
  },
  {
    id: "S12-22",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Review budget versus actual/remaining forecast",
    proposedOwnerRole: "Finance/PM",
    completionOutputOrEvidence: "Reconciled project forecast.",
  },
  {
    id: "S12-23",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Assign outstanding obligations, disputes and incidents",
    proposedOwnerRole: "PM",
    completionOutputOrEvidence: "Owner, next action and due date for each open item.",
  },
  {
    id: "S12-24",
    stageNumber: 12,
    stageCode: "STAGE-12",
    name: "Approve operational close and handover reporting pack",
    proposedOwnerRole: "Configured reviewers/PM",
    completionOutputOrEvidence: "Closure scope, conditions and report-ready data.",
  },
  {
    id: "S13-01",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Confirm report audience, scope and actual due dates",
    proposedOwnerRole: "PM/reporting lead",
    completionOutputOrEvidence: "Contract/project-specific reporting brief.",
  },
  {
    id: "S13-02",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Confirm measurement definitions and periods",
    proposedOwnerRole: "Reporting lead",
    completionOutputOrEvidence: "Metric definition versions.",
  },
  {
    id: "S13-03",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Reconcile attendance and entry-source measures",
    proposedOwnerRole: "Reporting/operations",
    completionOutputOrEvidence: "Defined counts with reconciliation status.",
  },
  {
    id: "S13-04",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Reconcile marketing/engagement data",
    proposedOwnerRole: "Marketing/reporting",
    completionOutputOrEvidence: "Source/period/attribution notes.",
  },
  {
    id: "S13-05",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Review delivery evidence against requirements",
    proposedOwnerRole: "PM/quality",
    completionOutputOrEvidence: "Delivered/partial/not-delivered register.",
  },
  {
    id: "S13-06",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Review sponsor, partner and IP obligations",
    proposedOwnerRole: "Partnership/commercial",
    completionOutputOrEvidence: "Actual fulfilment evidence.",
  },
  {
    id: "S13-07",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Select authorised photos/video and asset rights",
    proposedOwnerRole: "Content/communications",
    completionOutputOrEvidence: "Approved report asset set.",
  },
  {
    id: "S13-08",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Summarise operational performance and incidents safely",
    proposedOwnerRole: "Operations/HSE",
    completionOutputOrEvidence: "Approved audience-specific summary.",
  },
  {
    id: "S13-09",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Review stakeholder and visitor feedback",
    proposedOwnerRole: "Experience/reporting",
    completionOutputOrEvidence: "Qualified feedback findings.",
  },
  {
    id: "S13-10",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Prepare financial summary with declared basis",
    proposedOwnerRole: "Finance",
    completionOutputOrEvidence: "Contribution/margin/cash views and open costs.",
  },
  {
    id: "S13-11",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Explain budget and schedule variances",
    proposedOwnerRole: "PM/finance/planner",
    completionOutputOrEvidence: "Supported variance commentary.",
  },
  {
    id: "S13-12",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Draft client report from accepted sources",
    proposedOwnerRole: "Reporting lead",
    completionOutputOrEvidence: "Traceable report draft.",
  },
  {
    id: "S13-13",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Draft confidential internal project review",
    proposedOwnerRole: "PM/management",
    completionOutputOrEvidence: "Internal performance and risk review.",
  },
  {
    id: "S13-14",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Evaluate suppliers and subcontractors",
    proposedOwnerRole: "Procurement/package owners",
    completionOutputOrEvidence: "Evidence-based evaluations.",
  },
  {
    id: "S13-15",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Evaluate team/process performance",
    proposedOwnerRole: "PM/department leads",
    completionOutputOrEvidence: "Constructive operational review.",
  },
  {
    id: "S13-16",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Review lessons and corrective actions",
    proposedOwnerRole: "Management/PM",
    completionOutputOrEvidence: "Owned lessons with evidence.",
  },
  {
    id: "S13-17",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Obtain internal report and publication approval",
    proposedOwnerRole: "Configured reviewers",
    completionOutputOrEvidence: "Version-bound approvals.",
  },
  {
    id: "S13-18",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Publish final client deliverables",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Issued report/assets and recipients.",
  },
  {
    id: "S13-19",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Record client acceptance or requested revisions",
    proposedOwnerRole: "Client coordinator",
    completionOutputOrEvidence: "Actual response and revision actions.",
  },
  {
    id: "S13-20",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Review closure criteria by dimension",
    proposedOwnerRole: "PM/finance/management",
    completionOutputOrEvidence: "Operational/reporting/financial status decision.",
  },
  {
    id: "S13-21",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Assign and monitor residual claims or payments",
    proposedOwnerRole: "Finance/commercial",
    completionOutputOrEvidence: "Accountable settlement action plan.",
  },
  {
    id: "S13-22",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Archive or retain records under applicable policy",
    proposedOwnerRole: "Document/privacy owner",
    completionOutputOrEvidence: "Retention/hold classification.",
  },
  {
    id: "S13-23",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Promote reviewed lessons and benchmarks to templates",
    proposedOwnerRole: "Template owners",
    completionOutputOrEvidence: "New proposed template/rate reference version.",
  },
  {
    id: "S13-24",
    stageNumber: 13,
    stageCode: "STAGE-13",
    name: "Close, continue periodic reporting or reopen with reason",
    proposedOwnerRole: "Authorised owner",
    completionOutputOrEvidence: "Accurate lifecycle decision and next obligations.",
  },
];

/**
 * Returns all activities defined for a specific stage number (1..13).
 */
export function getActivitiesForStage(stageNumber: number): StageActivityDefinition[] {
  return ALL_STAGE_ACTIVITIES.filter((a) => a.stageNumber === stageNumber);
}

/**
 * Returns an activity definition by its normative ID (e.g. "S01-01").
 */
export function getActivityById(id: string): StageActivityDefinition | undefined {
  return ALL_STAGE_ACTIVITIES.find((a) => a.id === id);
}

/**
 * Instantiates the default activities for a project across the given stages.
 */
export function instantiateProjectActivities(
  projectId: string,
  stageNumbers: number[] = Array.from({ length: 13 }, (_, i) => i + 1),
  excludedActivityIds: string[] = []
): InstantiatedActivity[] {
  const excludedSet = new Set(excludedActivityIds);
  return ALL_STAGE_ACTIVITIES
    .filter((a) => stageNumbers.includes(a.stageNumber) && !excludedSet.has(a.id))
    .map((def) => ({
      ...def,
      instanceId: `act-${projectId}-${def.id.toLowerCase()}`,
      projectId,
      status: 'not_started' as ActivityStatus,
    }));
}

/**
 * Calculates stage progress metrics from instantiated activities.
 */
export function calculateStageProgress(activities: InstantiatedActivity[], stageNumber: number): {
  total: number;
  completed: number;
  inProgress: number;
  blocked: number;
  percent: number;
} {
  const stageActs = activities.filter((a) => a.stageNumber === stageNumber);
  const total = stageActs.length;
  if (total === 0) return { total: 0, completed: 0, inProgress: 0, blocked: 0, percent: 100 };

  const completed = stageActs.filter((a) => a.status === 'completed' || a.status === 'waived_by_exception').length;
  const inProgress = stageActs.filter((a) => a.status === 'in_progress').length;
  const blocked = stageActs.filter((a) => a.status === 'blocked').length;
  const percent = Math.round((completed / total) * 100);

  return { total, completed, inProgress, blocked, percent };
}
