export type ControlKind = 'requirements' | 'clarifications' | 'observations';
export interface ControlList<T> { data: T[]; meta?: {capabilities?: Record<string, any>; truncated?: boolean; limit?: number} }
export interface RequirementInput { title:string; originalWording:string; interpretation?:string|null; sourceType:'manual'|'client_note'|'source_reference'; sourceReference?:string|null; category?:string|null; quantity?:string|null; unit?:string|null; locationZone?:string|null; acceptanceCriteria?:string|null; ownerId?:string|null; reason:string }
export interface IntakeRequirement extends Omit<RequirementInput,'reason'> { id:string;projectId:string;code:string|null;rowVersion:number;currentRevision:number;provenanceState:string;sourceVerification:string;status:string;isApproved:boolean;canRevise:boolean }
export interface IntakeRevision {id:string;revisionNumber:number;snapshot:Omit<RequirementInput,'reason'>|null;snapshotHash:string|null;reason:string;authorId:string|null;createdAt:string;provenanceState:string}
export interface ClarificationInput {question:string;sourceAttribution:string;ownerId:string;respondentId?:string|null;requirementId?:string|null;dueAt?:string|null;reason:string}
export interface ClarificationRecord {id:string;projectId:string;question:string;sourceAttribution:string;ownerId:string;respondentId?:string|null;requirementId?:string|null;dueAt?:string|null;status:string;rowVersion:number;createdAt:string;updatedAt:string;canRespond:boolean;canReopen:boolean;provenanceState:string;latestResponse?:any;responses?:any[];history?:any[];historyTruncated?:boolean;responsesTruncated?:boolean}
export interface FieldNoteInput {clientOperationId:string;deviceId:string;capturedAt:string;taskId?:string;baseVersion?:number;note:string;reason:string}
export interface FieldNoteReceipt extends Omit<FieldNoteInput,'taskId'|'baseVersion'> {taskId:string|null;baseVersion:number|null;id:string;organisationId:string;projectId:string;actorId:string;receivedAt:string;clientTimestampClaimed:true;deviceIdClaimed:true;contractVersion:'field-observation.v1';currentTaskVersion:number|null;status:'accepted'|'accepted_as_observation_with_conflict';payloadHash:string;auditEventId:string;eventId:string;authorityEffect:'observation_only'}
