export type RecordsKind = 'work' | 'documents' | 'reports';
export interface RecordsEnvelope<T> { data: T[]; meta?: { capabilities?: Record<string, any> } }
export interface WorkPackageRecord { id: string; name: string; ownerName?: string; ownerId: string; status: string; acceptanceState: string; rowVersion: number }
export interface TaskRecord { id: string; packageId: string; title: string; assigneeId?: string; assigneeName?: string; state: string; isCompleted: boolean; rowVersion: number; completionEvidence?: string; canComplete?: boolean }
export interface DocumentRecord { id: string; title: string; discipline: string; documentType: string; confidentialityLevel: string; rowVersion: number; status: string; fileState: string; revisionsCount: number; revisions?: DocumentRevision[] }
export interface DocumentRevision { id: string; revisionCode: string; originalFilename?: string; changeSummary?: string; scanStatus?: string; fileState: string; createdAt?: string }
export interface ReportRecord { id: string; rootReportId: string; projectId: string; reportCode: string; version: number; status: string; targetAudience: string; periodStart: string; periodEnd: string; asOf: string; contentHash: string; createdAt: string; revisionReason: string; canRevise?: boolean }
export interface ReportDetail extends ReportRecord { snapshot: { project: { title: string; maturity: string; outcome: string; rowVersion: number }; stages: Array<{ id: string; stageNumber: number; stageName: string; status: string; progressPercent: number }>; activityCounts: Record<string, number>; sourceManifest: Array<{ type: string; id: string; version?: number; updatedAt?: string }>; limitations: string[] }; history: ReportRecord[] }
export interface PortfolioSummary { asOf: string; projectCount: number; editorProjectCount: number; viewerProjectCount: number; reportCount: number; reportVersionCount: number; maturityDistribution: Array<{ key: string; count: number }>; outcomeDistribution: Array<{ key: string; count: number }>; projects: Array<{ id: string; projectCode: string; title: string; maturity: string; outcome: string; rowVersion: number; updatedAt: string; accessLevel: string; reportCount: number }>; limitations: string[] }
