-- Progressive Scope & Requirements Management Migration
ALTER TABLE requirements
  ADD COLUMN IF NOT EXISTS code TEXT,
  ADD COLUMN IF NOT EXISTS original_wording TEXT,
  ADD COLUMN IF NOT EXISTS interpretation TEXT,
  ADD COLUMN IF NOT EXISTS source_type TEXT DEFAULT 'Client RFP',
  ADD COLUMN IF NOT EXISTS scope_package TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'staging_technical',
  ADD COLUMN IF NOT EXISTS discipline TEXT,
  ADD COLUMN IF NOT EXISTS department TEXT,
  ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS risk TEXT DEFAULT 'low',
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft',
  ADD COLUMN IF NOT EXISTS progress INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS acceptance_criteria TEXT,
  ADD COLUMN IF NOT EXISTS quantity NUMERIC,
  ADD COLUMN IF NOT EXISTS unit TEXT,
  ADD COLUMN IF NOT EXISTS location_zone TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS milestone TEXT,
  ADD COLUMN IF NOT EXISTS dependency TEXT,
  ADD COLUMN IF NOT EXISTS responsible_party TEXT DEFAULT 'e3',
  ADD COLUMN IF NOT EXISTS external_responsible_party TEXT,
  ADD COLUMN IF NOT EXISTS primary_owner_id UUID REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS approver_id UUID REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS current_revision INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archived_by UUID REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS linked_document_id TEXT,
  ADD COLUMN IF NOT EXISTS linked_document_number TEXT,
  ADD COLUMN IF NOT EXISTS linked_design_id TEXT,
  ADD COLUMN IF NOT EXISTS linked_design_version TEXT,
  ADD COLUMN IF NOT EXISTS linked_boq_line_code TEXT,
  ADD COLUMN IF NOT EXISTS linked_task_id TEXT,
  ADD COLUMN IF NOT EXISTS target_cost_qar NUMERIC,
  ADD COLUMN IF NOT EXISTS delivery_evidence_hash TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS requirement_revisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  organisation_id UUID NOT NULL REFERENCES organisations(id),
  project_id UUID NOT NULL REFERENCES projects(id),
  revision_number INTEGER NOT NULL,
  changed_fields JSONB NOT NULL,
  previous_values JSONB NOT NULL,
  new_values JSONB NOT NULL,
  reason_for_change TEXT NOT NULL,
  impact JSONB,
  author_id UUID REFERENCES users(id),
  author_name TEXT,
  author_role TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS requirement_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  organisation_id UUID NOT NULL REFERENCES organisations(id),
  project_id UUID NOT NULL REFERENCES projects(id),
  file_name TEXT NOT NULL,
  file_size INTEGER,
  mime_type TEXT,
  file_url TEXT,
  storage_key TEXT,
  media_category TEXT NOT NULL,
  version TEXT DEFAULT 'Rev 01',
  uploaded_by UUID REFERENCES users(id),
  uploaded_by_name TEXT,
  description TEXT,
  approval_status TEXT DEFAULT 'draft',
  is_current BOOLEAN DEFAULT TRUE,
  related_design_package_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS requirement_relationships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  target_requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  relationship_type TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bulk_import_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id UUID NOT NULL REFERENCES organisations(id),
  project_id UUID NOT NULL REFERENCES projects(id),
  file_name TEXT,
  total_rows INTEGER DEFAULT 0,
  valid_rows INTEGER DEFAULT 0,
  invalid_rows INTEGER DEFAULT 0,
  imported_rows INTEGER DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'uploaded',
  errors JSONB,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS document_parsing_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id UUID NOT NULL REFERENCES organisations(id),
  project_id UUID NOT NULL REFERENCES projects(id),
  source_document_id TEXT,
  source_document_name TEXT,
  document_type TEXT,
  status TEXT NOT NULL DEFAULT 'review_ready',
  extracted_text TEXT,
  total_extracted INTEGER DEFAULT 0,
  approved_count INTEGER DEFAULT 0,
  rejected_count INTEGER DEFAULT 0,
  clarification_count INTEGER DEFAULT 0,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS extraction_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL REFERENCES document_parsing_jobs(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES projects(id),
  organisation_id UUID NOT NULL REFERENCES organisations(id),
  candidate_code TEXT,
  title TEXT NOT NULL,
  description TEXT,
  scope_package TEXT,
  suggested_category TEXT,
  suggested_discipline TEXT,
  suggested_department TEXT,
  suggested_owner_id UUID REFERENCES users(id),
  suggested_owner_name TEXT,
  source_page INTEGER,
  source_section TEXT,
  source_clause TEXT,
  source_reference TEXT,
  source_quote TEXT,
  confidence_score NUMERIC(4,3) DEFAULT 0.900,
  extracted_quantities TEXT,
  extracted_unit TEXT,
  extracted_dates TEXT,
  extracted_responsibilities TEXT,
  extracted_acceptance_criteria TEXT,
  suggested_deliverables TEXT,
  suggested_tasks TEXT,
  suggested_milestones TEXT,
  suggested_design_media TEXT,
  suggested_clarifications TEXT,
  potential_duplicate_of TEXT,
  conflict_notes TEXT,
  review_status TEXT DEFAULT 'pending',
  converted_requirement_id UUID REFERENCES requirements(id),
  converted_clarification_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
