import { pgTable, text, timestamp, uuid, boolean, integer, numeric, jsonb } from 'drizzle-orm/pg-core';
import { organisations, users } from './identity.js';
import { projects } from './projects.js';

export const requirements = pgTable('requirements', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  code: text('code'),
  title: text('title').notNull(),
  description: text('description').notNull(),
  originalWording: text('original_wording'),
  interpretation: text('interpretation'),
  sourceType: text('source_type').default('Client RFP'),
  sourceReference: text('source_reference'),
  scopePackage: text('scope_package'),
  category: text('category').default('staging_technical'),
  discipline: text('discipline'),
  department: text('department'),
  ownerId: uuid('owner_id').references(() => users.id),
  primaryOwnerId: uuid('primary_owner_id').references(() => users.id),
  approverId: uuid('approver_id').references(() => users.id),
  priority: text('priority').default('medium'),
  risk: text('risk').default('low'),
  status: text('status').default('draft'),
  progress: integer('progress').default(0),
  acceptanceCriteria: text('acceptance_criteria'),
  quantity: numeric('quantity'),
  unit: text('unit'),
  locationZone: text('location_zone'),
  notes: text('notes'),
  dueDate: timestamp('due_date', { withTimezone: true }),
  startDate: timestamp('start_date', { withTimezone: true }),
  milestone: text('milestone'),
  dependency: text('dependency'),
  responsibleParty: text('responsible_party').default('e3'),
  externalResponsibleParty: text('external_responsible_party'),
  deliverablePackageId: uuid('deliverable_package_id'),
  disposition: text('disposition').default('applicability_unknown').notNull(),
  isApproved: boolean('is_approved').default(false),
  currentRevision: integer('current_revision').default(1),
  isArchived: boolean('is_archived').default(false),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  archivedBy: uuid('archived_by').references(() => users.id),
  linkedDocumentId: text('linked_document_id'),
  linkedDocumentNumber: text('linked_document_number'),
  linkedDesignId: text('linked_design_id'),
  linkedDesignVersion: text('linked_design_version'),
  linkedBoqLineCode: text('linked_boq_line_code'),
  linkedTaskId: text('linked_task_id'),
  targetCostQar: numeric('target_cost_qar'),
  deliveryEvidenceHash: text('delivery_evidence_hash'),
  allocatedQuantity: numeric('allocated_quantity'),
  designApprovedQuantity: numeric('design_approved_quantity'),
  releasedQuantity: numeric('released_quantity'),
  producedQuantity: numeric('produced_quantity'),
  deliveredQuantity: numeric('delivered_quantity'),
  installedQuantity: numeric('installed_quantity'),
  acceptedQuantity: numeric('accepted_quantity'),
  allocationStatus: text('allocation_status').default('unallocated'),
  designStatus: text('design_status').default('required'),
  productionStatus: text('production_status').default('not_released'),
  logisticsStatus: text('logistics_status').default('pending'),
  installationStatus: text('installation_status').default('not_started'),
  quantityComparator: text('quantity_comparator').default('exact'),
  quantityBasis: text('quantity_basis').default('unspecified'),
  sourceEvidenceSpans: jsonb('source_evidence_spans').default([]),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const requirementRevisions = pgTable('requirement_revisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  requirementId: uuid('requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  revisionNumber: integer('revision_number').notNull(),
  changedFields: jsonb('changed_fields').notNull(),
  previousValues: jsonb('previous_values').notNull(),
  newValues: jsonb('new_values').notNull(),
  reasonForChange: text('reason_for_change').notNull(),
  impact: jsonb('impact'),
  authorId: uuid('author_id').references(() => users.id),
  authorName: text('author_name'),
  authorRole: text('author_role'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const requirementAttachments = pgTable('requirement_attachments', {
  id: uuid('id').primaryKey().defaultRandom(),
  requirementId: uuid('requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  fileName: text('file_name').notNull(),
  fileSize: integer('file_size'),
  mimeType: text('mime_type'),
  fileUrl: text('file_url'),
  storageKey: text('storage_key'),
  mediaCategory: text('media_category').notNull(),
  version: text('version').default('Rev 01'),
  uploadedBy: uuid('uploaded_by').references(() => users.id),
  uploadedByName: text('uploaded_by_name'),
  description: text('description'),
  approvalStatus: text('approval_status').default('draft'),
  isCurrent: boolean('is_current').default(true),
  relatedDesignPackageId: text('related_design_package_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const requirementRelationships = pgTable('requirement_relationships', {
  id: uuid('id').primaryKey().defaultRandom(),
  sourceRequirementId: uuid('source_requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  targetRequirementId: uuid('target_requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  relationshipType: text('relationship_type').notNull(),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const bulkImportJobs = pgTable('bulk_import_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  fileName: text('file_name'),
  totalRows: integer('total_rows').default(0),
  validRows: integer('valid_rows').default(0),
  invalidRows: integer('invalid_rows').default(0),
  importedRows: integer('imported_rows').default(0),
  status: text('status').default('uploaded').notNull(),
  errors: jsonb('errors'),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const documentParsingJobs = pgTable('document_parsing_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  sourceDocumentId: text('source_document_id'),
  sourceDocumentName: text('source_document_name'),
  documentType: text('document_type'),
  status: text('status').default('review_ready').notNull(),
  extractedText: text('extracted_text'),
  totalExtracted: integer('total_extracted').default(0),
  approvedCount: integer('approved_count').default(0),
  rejectedCount: integer('rejected_count').default(0),
  clarificationCount: integer('clarification_count').default(0),
  parserVersion: text('parser_version').default('v3.0.0-neural-structured'),
  modelProvider: text('model_provider').default('deterministic-structured'),
  tokenCostMetadata: jsonb('token_cost_metadata'),
  structureSummary: jsonb('structure_summary'),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const extractionCandidates = pgTable('extraction_candidates', {
  id: uuid('id').primaryKey().defaultRandom(),
  jobId: uuid('job_id').references(() => documentParsingJobs.id, { onDelete: 'cascade' }).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  candidateCode: text('candidate_code'),
  queueType: text('queue_type').default('master_scope_requirements'),
  candidateType: text('candidate_type').default('master_requirement'),
  title: text('title').notNull(),
  description: text('description'),
  originalWording: text('original_wording'),
  scopePackage: text('scope_package'),
  suggestedCategory: text('suggested_category'),
  suggestedDiscipline: text('suggested_discipline'),
  suggestedDepartment: text('suggested_department'),
  suggestedOwnerId: uuid('suggested_owner_id').references(() => users.id),
  suggestedOwnerName: text('suggested_owner_name'),
  sourcePage: integer('source_page'),
  sourceSection: text('source_section'),
  sourceClause: text('source_clause'),
  sourceReference: text('source_reference'),
  sourceQuote: text('source_quote'),
  sourceProvenance: jsonb('source_provenance'),
  fieldAttributions: jsonb('field_attributions'),
  confidenceScore: numeric('confidence_score', { precision: 4, scale: 3 }).default('0.900'),
  confidenceBreakdown: jsonb('confidence_breakdown'),
  extractedQuantities: text('extracted_quantities'),
  extractedUnit: text('extracted_unit'),
  unallocatedQuantity: numeric('unallocated_quantity'),
  suggestedAllocations: jsonb('suggested_allocations'),
  designRequired: boolean('design_required').default(false),
  clientApprovalRequired: boolean('client_approval_required').default(false),
  fabricationRequired: boolean('fabrication_required').default(false),
  deliveryRequired: boolean('delivery_required').default(false),
  installationRequired: boolean('installation_required').default(false),
  extractedDates: text('extracted_dates'),
  extractedResponsibilities: text('extracted_responsibilities'),
  extractedAcceptanceCriteria: text('extracted_acceptance_criteria'),
  suggestedDeliverables: text('suggested_deliverables'),
  suggestedTasks: text('suggested_tasks'),
  suggestedMilestones: text('suggested_milestones'),
  suggestedDesignMedia: text('suggested_design_media'),
  suggestedClarifications: text('suggested_clarifications'),
  potentialDuplicateOf: text('potential_duplicate_of'),
  conflictNotes: text('conflict_notes'),
  missingFields: jsonb('missing_fields').default([]),
  reviewStatus: text('review_status').default('pending'),
  reviewerNotes: text('reviewer_notes'),
  convertedRequirementId: uuid('converted_requirement_id').references(() => requirements.id),
  convertedClarificationId: text('converted_clarification_id'),
  quantityComparator: text('quantity_comparator').default('exact'),
  quantityBasis: text('quantity_basis').default('unspecified'),
  sourceEvidenceSpans: jsonb('source_evidence_spans').default([]),
  unresolvedIssues: jsonb('unresolved_issues').default([]),
  blockingIssues: jsonb('blocking_issues').default([]),
  proposedAction: text('proposed_action'),
  modality: text('modality').default('mandatory'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const extractedDocumentBlocks = pgTable('extracted_document_blocks', {
  id: uuid('id').primaryKey().defaultRandom(),
  jobId: uuid('job_id').references(() => documentParsingJobs.id, { onDelete: 'cascade' }).notNull(),
  pageNumber: integer('page_number').notNull(),
  sectionNumber: text('section_number'),
  clauseNumber: text('clause_number'),
  sheetName: text('sheet_name'),
  tableId: text('table_id'),
  slideNumber: integer('slide_number'),
  blockType: text('block_type').notNull(),
  rawText: text('raw_text').notNull(),
  boundingBox: jsonb('bounding_box'),
  extractionMethod: text('extraction_method').default('deterministic_text'),
  ocrConfidence: numeric('ocr_confidence', { precision: 4, scale: 3 }).default('0.980'),
  sequenceIndex: integer('sequence_index').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const documentComparisons = pgTable('document_comparisons', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  priorJobId: text('prior_job_id'),
  priorDocumentName: text('prior_document_name'),
  newJobId: text('new_job_id').notNull(),
  newDocumentName: text('new_document_name').notNull(),
  changeType: text('change_type').notNull(),
  deltaData: jsonb('delta_data').notNull(),
  reviewStatus: text('review_status').default('pending').notNull(),
  appliedRevisionId: uuid('applied_revision_id').references(() => requirementRevisions.id),
  reviewedBy: uuid('reviewed_by').references(() => users.id),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const clarifications = pgTable('clarifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  question: text('question').notNull(),
  source: text('source').notNull(),
  dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
  response: text('response'),
  respondedBy: uuid('responded_by').references(() => users.id),
  status: text('status').default('open').notNull(), // 'open', 'answered', 'superseded'
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const risks = pgTable('risks', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  description: text('description').notNull(),
  severity: text('severity').notNull(), // 'low', 'medium', 'high', 'critical'
  likelihood: text('likelihood').notNull(), // 'low', 'medium', 'high'
  mitigation: text('mitigation'),
  ownerId: uuid('owner_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const qualificationDecisions = pgTable('qualification_decisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  decision: text('decision').notNull(), // 'pursue', 'pause', 'no_go'
  rationale: text('rationale').notNull(),
  decidedBy: uuid('decided_by').references(() => users.id).notNull(),
  decidedAt: timestamp('decided_at', { withTimezone: true }).defaultNow().notNull(),
});

// =========================================================================
// PHASE 2: ADDITIVE TABLES FOR GROUPING, ALLOCATION & FULFILMENT
// =========================================================================

export const requirementAllocations = pgTable('requirement_allocations', {
  id: uuid('id').primaryKey().defaultRandom(),
  requirementId: uuid('requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  zone: text('zone').notNull(),
  location: text('location').notNull(),
  subLocation: text('sub_location'),
  quantity: numeric('quantity').notNull(),
  unit: text('unit').default('pcs'),
  designVariantId: text('design_variant_id'),
  requiredDate: timestamp('required_date', { withTimezone: true }),
  installationDate: timestamp('installation_date', { withTimezone: true }),
  locationNotes: text('location_notes'),
  status: text('status').default('unassigned').notNull(), // 'unassigned', 'assigned', 'in_progress', 'installed', 'accepted'
  responsibleTeam: text('responsible_team'),
  completionPct: integer('completion_pct').default(0).notNull(),
  evidenceRef: text('evidence_ref'),
  revision: integer('revision').default(1).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const designPackages = pgTable('design_packages', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  title: text('title').notNull(),
  discipline: text('discipline'),
  leadDesignerId: uuid('lead_designer_id').references(() => users.id),
  leadDesignerName: text('lead_designer_name'),
  brief: text('brief'),
  specifications: text('specifications'),
  materials: text('materials'),
  finishes: text('finishes'),
  dimensions: text('dimensions'),
  revision: integer('revision').default(1).notNull(),
  status: text('status').default('in_progress').notNull(),
  internalApproval: boolean('internal_approval').default(false).notNull(),
  clientApproval: boolean('client_approval').default(false).notNull(),
  productionReleaseStatus: text('production_release_status').default('not_released').notNull(),
  approvedQuantity: numeric('approved_quantity').default('0').notNull(),
  releasedQuantity: numeric('released_quantity').default('0').notNull(),
  linkedRequirementIds: jsonb('linked_requirement_ids').default([]).notNull(),
  linkedAllocationIds: jsonb('linked_allocation_ids').default([]).notNull(),
  comments: jsonb('comments').default([]).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const designVariants = pgTable('design_variants', {
  id: uuid('id').primaryKey().defaultRandom(),
  designPackageId: uuid('design_package_id').references(() => designPackages.id, { onDelete: 'cascade' }),
  requirementId: uuid('requirement_id').references(() => requirements.id, { onDelete: 'cascade' }),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  name: text('name').notNull(),
  code: text('code'),
  dimensions: text('dimensions'),
  materials: text('materials'),
  finish: text('finish'),
  media: jsonb('media').default([]).notNull(),
  quantity: numeric('quantity').default('0').notNull(),
  approvedQuantity: numeric('approved_quantity').default('0').notNull(),
  releasedQuantity: numeric('released_quantity').default('0').notNull(),
  approvalStatus: text('approval_status').default('draft').notNull(), // 'draft', 'client_review', 'approved', 'rejected', 'superseded'
  productionReleaseStatus: text('production_release_status').default('not_released').notNull(),
  linkedAllocationIds: jsonb('linked_allocation_ids').default([]).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const fulfilmentItems = pgTable('fulfilment_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  requirementId: uuid('requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  allocationId: uuid('allocation_id').references(() => requirementAllocations.id, { onDelete: 'set null' }),
  designPackageId: uuid('design_package_id').references(() => designPackages.id, { onDelete: 'set null' }),
  designVariantId: uuid('design_variant_id').references(() => designVariants.id, { onDelete: 'set null' }),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  itemDescription: text('item_description').notNull(),
  quantity: numeric('quantity').notNull(),
  unit: text('unit').default('pcs'),
  classification: text('classification').default('make').notNull(), // 'make', 'buy', 'rent'
  material: text('material'),
  department: text('department'),
  responsibleOwnerId: uuid('responsible_owner_id').references(() => users.id),
  responsibleOwnerName: text('responsible_owner_name'),
  supplierId: text('supplier_id'),
  boqLineCode: text('boq_line_code'),
  productionStatus: text('production_status').default('not_started').notNull(),
  qcStatus: text('qc_status').default('pending').notNull(),
  requiredDate: timestamp('required_date', { withTimezone: true }),
  notes: text('notes'),
  evidence: text('evidence'),
  status: text('status').default('draft_review').notNull(), // 'draft_review', 'approved', 'rejected', 'released'
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const departmentWorkPackages = pgTable('department_work_packages', {
  id: uuid('id').primaryKey().defaultRandom(),
  requirementId: uuid('requirement_id').references(() => requirements.id, { onDelete: 'cascade' }).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  title: text('title').notNull(),
  department: text('department').notNull(),
  responsibleOwnerId: uuid('responsible_owner_id').references(() => users.id),
  responsibleOwnerName: text('responsible_owner_name'),
  supportingDepartment: text('supporting_department'),
  supportingUserIds: jsonb('supporting_user_ids').default([]).notNull(),
  approverId: uuid('approver_id').references(() => users.id),
  approverName: text('approver_name'),
  startDate: timestamp('start_date', { withTimezone: true }),
  dueDate: timestamp('due_date', { withTimezone: true }),
  status: text('status').default('pending').notNull(), // 'pending', 'in_progress', 'blocked', 'completed'
  progress: integer('progress').default(0).notNull(),
  dependency: text('dependency'),
  deliverables: text('deliverables'),
  evidenceRef: text('evidence_ref'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const productionBatches = pgTable('production_batches', {
  id: uuid('id').primaryKey().defaultRandom(),
  organisationId: uuid('organisation_id').references(() => organisations.id).notNull(),
  projectId: uuid('project_id').references(() => projects.id).notNull(),
  batchCode: text('batch_code').notNull(),
  designVariantId: uuid('design_variant_id').references(() => designVariants.id, { onDelete: 'set null' }),
  status: text('status').default('draft').notNull(),
  releasedQuantity: numeric('released_quantity').notNull(),
  producedQuantity: numeric('produced_quantity').default('0').notNull(),
  qcPassedQuantity: numeric('qc_passed_quantity').default('0').notNull(),
  deliveredQuantity: numeric('delivered_quantity').default('0').notNull(),
  installedQuantity: numeric('installed_quantity').default('0').notNull(),
  acceptedQuantity: numeric('accepted_quantity').default('0').notNull(),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const productionBatchItems = pgTable('production_batch_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  batchId: uuid('batch_id').references(() => productionBatches.id, { onDelete: 'cascade' }).notNull(),
  fulfilmentItemId: uuid('fulfilment_item_id').references(() => fulfilmentItems.id, { onDelete: 'set null' }),
  allocationId: uuid('allocation_id').references(() => requirementAllocations.id, { onDelete: 'set null' }),
  quantity: numeric('quantity').notNull(),
  destinationZone: text('destination_zone'),
  destinationLocation: text('destination_location'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const parserDecisionMemory = pgTable('parser_decision_memory', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id, { onDelete: 'cascade' }).notNull(),
  candidateSignature: text('candidate_signature').notNull(),
  targetRequirementId: uuid('target_requirement_id').references(() => requirements.id, { onDelete: 'set null' }),
  decisionAction: text('decision_action').notNull(),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const scopeImportBatches = pgTable('scope_import_batches', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  organisationId: uuid('organisation_id').references(() => organisations.id, { onDelete: 'cascade' }).notNull(),
  jobId: text('job_id').notNull(),
  idempotencyKey: text('idempotency_key').notNull(),
  status: text('status').default('published').notNull(),
  publishedRequirementIds: jsonb('published_requirement_ids').default([]).notNull(),
  publishedAllocationIds: jsonb('published_allocation_ids').default([]).notNull(),
  publishedEvidenceLinksCount: integer('published_evidence_links_count').default(0).notNull(),
  publishedRevisionsCount: integer('published_revisions_count').default(0).notNull(),
  publishedBy: text('published_by'),
  publishedAt: timestamp('published_at', { withTimezone: true }).defaultNow().notNull(),
  rollbackReason: text('rollback_reason'),
  rolledBackAt: timestamp('rolled_back_at', { withTimezone: true }),
});



